// GENERATED by docs/design/service-icons/build.mjs. Edit the icon there and
// re-run it; do not edit this file by hand.
//
// The service icons: one front-facing package per service on the site's
// notched plate, in the blue ramp, with a lit ink core and one amber LED.
// Drawn on a 64-unit grid; render at any size from 16 px up.
import type { SVGProps } from "react";

export type ServiceIconProps = Omit<SVGProps<SVGSVGElement>, "width" | "height"> & {
    /** Rendered width and height in px. */
    size?: number;
    /** Accessible name; pass an empty string for a purely decorative icon. */
    title?: string;
};

function frame(size: number, title: string, rest: Omit<ServiceIconProps, "size" | "title">) {
    return {
        viewBox: "0 0 64 64",
        width: size,
        height: size,
        role: title ? "img" : undefined,
        "aria-label": title || undefined,
        "aria-hidden": title ? undefined : true,
        ...rest,
    } as const;
}

/** Compute. */
export function ComputeIcon({ size = 40, title = "Compute", ...rest }: ServiceIconProps) {
    return (
        <svg {...frame(size, title, rest)}>
        <defs>
          <linearGradient id="cp-tile" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1c1c24"/><stop offset="1" stopColor="#0c0c10"/></linearGradient>
          <radialGradient id="cp-glow" cx="32" cy="30" r="26" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#0095ff" stopOpacity="0.36"/><stop offset="1" stopColor="#0095ff" stopOpacity="0"/></radialGradient>
          <filter id="cp-soft" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="1.5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
          <filter id="cp-drop" x="-50%" y="-50%" width="200%" height="200%"><feDropShadow dx="0" dy="2.5" stdDeviation="2.2" floodColor="#0095ff" floodOpacity="0.45"/></filter>
          <linearGradient id="cp-chip" x1="17" y1="17" x2="47" y2="47" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#2ea8ff"/><stop offset="1" stopColor="#1d4ed8"/></linearGradient>
          <linearGradient id="cp-core" x1="27" y1="27" x2="37" y2="37" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#8fd0ff"/><stop offset="1" stopColor="#0095ff"/></linearGradient>
        </defs>
          <path d="M8 0H64V56L56 64H0V8Z" fill="url(#cp-tile)"/>
          <path d="M8 0H64V56L56 64H0V8Z" fill="url(#cp-glow)"/>
          <path d="M8.5 0.5H63.5V55.8L55.8 63.5H0.5V8.2Z" fill="none" stroke="#ffffff" strokeOpacity="0.10"/>
          <path d="M9 1H63" stroke="#ffffff" strokeOpacity="0.14"/>
          <g fill="#7fc7ff" fillOpacity="0.9">
            <rect x="20.7" y="11.5" width="1.6" height="6.5"/><rect x="27.7" y="11.5" width="1.6" height="6.5"/><rect x="34.7" y="11.5" width="1.6" height="6.5"/><rect x="41.7" y="11.5" width="1.6" height="6.5"/>
            <rect x="20.7" y="46" width="1.6" height="6.5"/><rect x="27.7" y="46" width="1.6" height="6.5"/><rect x="34.7" y="46" width="1.6" height="6.5"/><rect x="41.7" y="46" width="1.6" height="6.5"/>
            <rect x="11.5" y="20.7" width="6.5" height="1.6"/><rect x="11.5" y="27.7" width="6.5" height="1.6"/><rect x="11.5" y="34.7" width="6.5" height="1.6"/><rect x="11.5" y="41.7" width="6.5" height="1.6"/>
            <rect x="46" y="20.7" width="6.5" height="1.6"/><rect x="46" y="27.7" width="6.5" height="1.6"/><rect x="46" y="34.7" width="6.5" height="1.6"/><rect x="46" y="41.7" width="6.5" height="1.6"/>
          </g>
          <rect x="17" y="17" width="30" height="30" rx="4" fill="url(#cp-chip)" filter="url(#cp-drop)"/>
          <rect x="17.5" y="17.5" width="29" height="29" rx="3.5" fill="none" stroke="#ffffff" strokeOpacity="0.22"/>
          <path d="M21 17.5H43" stroke="#ffffff" strokeOpacity="0.35" strokeWidth="0.8"/>
          <rect x="24" y="24" width="16" height="16" rx="2" fill="#fafaf4" filter="url(#cp-soft)"/>
          <rect x="27.5" y="27.5" width="9" height="9" rx="1" fill="url(#cp-core)"/>
          <circle cx="43" cy="21" r="1.25" fill="#f5b324" filter="url(#cp-soft)"/>
        </svg>
    );
}

/** GPU Pods. */
export function GpuPodsIcon({ size = 40, title = "GPU Pods", ...rest }: ServiceIconProps) {
    return (
        <svg {...frame(size, title, rest)}>
        <defs>
          <linearGradient id="gp-tile" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1c1c24"/><stop offset="1" stopColor="#0c0c10"/></linearGradient>
          <radialGradient id="gp-glow" cx="32" cy="30" r="26" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#0095ff" stopOpacity="0.36"/><stop offset="1" stopColor="#0095ff" stopOpacity="0"/></radialGradient>
          <filter id="gp-soft" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="1.5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
          <filter id="gp-drop" x="-50%" y="-50%" width="200%" height="200%"><feDropShadow dx="0" dy="2.5" stdDeviation="2.2" floodColor="#0095ff" floodOpacity="0.45"/></filter>
          <linearGradient id="gp-card" x1="12" y1="20" x2="48" y2="46" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#2ea8ff"/><stop offset="1" stopColor="#1d4ed8"/></linearGradient>
          <linearGradient id="gp-back" x1="16" y1="13" x2="52" y2="39" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#2757c9"/><stop offset="1" stopColor="#163b9c"/></linearGradient>
          <linearGradient id="gp-core" x1="26" y1="28" x2="34" y2="36" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#8fd0ff"/><stop offset="1" stopColor="#0095ff"/></linearGradient>
        </defs>
          <path d="M8 0H64V56L56 64H0V8Z" fill="url(#gp-tile)"/>
          <path d="M8 0H64V56L56 64H0V8Z" fill="url(#gp-glow)"/>
          <path d="M8.5 0.5H63.5V55.8L55.8 63.5H0.5V8.2Z" fill="none" stroke="#ffffff" strokeOpacity="0.10"/>
          <path d="M9 1H63" stroke="#ffffff" strokeOpacity="0.14"/>
          <rect x="16" y="13" width="36" height="26" rx="3" fill="url(#gp-back)" filter="url(#gp-drop)"/>
          <rect x="16.5" y="13.5" width="35" height="25" rx="2.5" fill="none" stroke="#ffffff" strokeOpacity="0.16"/>
          <g fill="#7fc7ff" fillOpacity="0.9">
            <rect x="16" y="46" width="1.6" height="4.5"/><rect x="19.5" y="46" width="1.6" height="4.5"/><rect x="23" y="46" width="1.6" height="4.5"/><rect x="26.5" y="46" width="1.6" height="4.5"/>
            <rect x="30" y="46" width="1.6" height="4.5"/><rect x="33.5" y="46" width="1.6" height="4.5"/><rect x="37" y="46" width="1.6" height="4.5"/><rect x="40.5" y="46" width="1.6" height="4.5"/>
          </g>
          <rect x="12" y="20" width="36" height="26" rx="3" fill="url(#gp-card)" filter="url(#gp-drop)"/>
          <rect x="12.5" y="20.5" width="35" height="25" rx="2.5" fill="none" stroke="#ffffff" strokeOpacity="0.22"/>
          <path d="M16 20.5H44" stroke="#ffffff" strokeOpacity="0.35" strokeWidth="0.8"/>
          <g fill="#8fd0ff" fillOpacity="0.9">
            <rect x="15.5" y="26" width="6" height="5" rx="0.8"/><rect x="15.5" y="33" width="6" height="5" rx="0.8"/>
            <rect x="38.5" y="26" width="6" height="5" rx="0.8"/><rect x="38.5" y="33" width="6" height="5" rx="0.8"/>
          </g>
          <rect x="24" y="25" width="12" height="14" rx="1.5" fill="#fafaf4" filter="url(#gp-soft)"/>
          <rect x="26.5" y="28" width="7" height="8" rx="0.8" fill="url(#gp-core)"/>
          <circle cx="44.5" cy="23" r="1.25" fill="#f5b324" filter="url(#gp-soft)"/>
        </svg>
    );
}
