export const BUILD_POLLING_STALE_BUILD_AGE_MS = 35 * 60 * 1000;
export const BUILD_POLLING_HEALTH_CHECK_MAX_ATTEMPTS = 6;
export const BUILD_POLLING_HEALTH_CHECK_INTERVAL_MS = 10_000;
export const BUILD_POLLING_FINALIZATION_GRACE_MS =
  BUILD_POLLING_HEALTH_CHECK_MAX_ATTEMPTS * BUILD_POLLING_HEALTH_CHECK_INTERVAL_MS + 15_000;
